// AUTOGENERATED CODE on 2026-02-20T22:51:59.566972 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(math_test_bio_code, BM_MATH_TEST_BIO_START, BM_MATH_TEST_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	21f",
    // --- inline asm end ---
    "21:", // main: @main
    "addi	sp, sp, -48",
    "sw	ra, 44(sp)", // 4-byte Folded Spill
    "sw	s0, 40(sp)", // 4-byte Folded Spill
    "sw	s1, 36(sp)", // 4-byte Folded Spill
    "lui	a1, 6",
    "lui	a3, 3",
    "li	t2, 1",
    "lui	s1, 1048396",
    "li	t0, -1",
    "lui	a4, 699051",
    // ERRATA BUG1 patch: lui	a5, 667542 (B1:phantom-rs1)
    "lui a5, 0xa2f06",
    "sw t0, -4(sp)",
    "addi t0, zero, 9",
    "slli t0, t0, 4",
    "slli t0, t0, 12",
    "add a5, a5, t0",
    "lw t0, -4(sp)",
    "lui	a2, 2",
    "lui	a0, 1048574",
    "addi	s0, a1, 1160",
    "sw	s0, 12(sp)", // 4-byte Folded Spill
    "addi	a3, a3, 580",
    "sw	a3, 32(sp)", // 4-byte Folded Spill
    "addi	a3, a4, -1365",
    "sw	a3, 4(sp)", // 4-byte Folded Spill
    "addi	a1, a1, 1159",
    "sw	a1, 16(sp)", // 4-byte Folded Spill
    "addi	a1, a5, 1317",
    "sw	a1, 8(sp)", // 4-byte Folded Spill
    "addi	a1, a2, -1757",
    "sw	a1, 28(sp)", // 4-byte Folded Spill
    "addi	ra, a0, 1758",
    "22:", // .LBB1_1: =>This Loop Header: Depth=1
    // Child Loop BB1_2 Depth 2
    // Child Loop BB1_4 Depth 2
    // Child Loop BB1_16 Depth 2
    // Child Loop BB1_18 Depth 2
    "li	a3, 0",
    "li	s0, 0",
    // --- inline asm begin ---
    "mv	a1, x16",
    // --- inline asm end ---
    "lw	a0, 32(sp)", // 4-byte Folded Reload
    // --- inline asm begin ---
    "mulh	a4, a1, a0",
    "mul	a1, a1, a0",
    // --- inline asm end ---
    "srli	a1, a1, 12",
    // ERRATA BUG2 patch: slli	a4, a4, 20 (shamt=20)
    "slli a4, a4, 19",
    "slli a4, a4, 1",
    "or	t1, a4, a1",
    "srai	a4, a4, 31",
    "xor	a5, t1, a4",
    "sub	a5, a5, a4",
    "li	a4, 31",
    "23:", // .LBB1_2: Parent Loop BB1_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "slli	a3, a3, 1",
    "srl	a1, a5, a4",
    "sll	a0, t2, a4",
    "addi	a4, a4, -1",
    "andi	a1, a1, 1",
    "or	a1, a1, a3",
    "srli	a3, a3, 14",
    "sltiu	a3, a3, 45",
    "addi	a3, a3, -1",
    "and	a0, a0, a3",
    "and	a3, a3, s1",
    "or	s0, s0, a0",
    "add	a3, a3, a1",
    "bne	a4, t0, 23b",
    // in Loop: Header=BB1_1 Depth=1
    "li	a1, 0",
    "li	a5, 0",
    "slli	a4, a3, 12",
    "li	a3, 31",
    "24:", // .LBB1_4: Parent Loop BB1_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "slli	a1, a1, 1",
    "srl	a0, a4, a3",
    "sll	a2, t2, a3",
    "addi	a3, a3, -1",
    "andi	a0, a0, 1",
    "or	a0, a0, a1",
    "srli	a1, a1, 14",
    "sltiu	a1, a1, 45",
    "addi	a1, a1, -1",
    "and	a2, a2, a1",
    "and	a1, a1, s1",
    "or	a5, a5, a2",
    "add	a1, a1, a0",
    "bne	a3, t0, 24b",
    // in Loop: Header=BB1_1 Depth=1
    "slli	a4, s0, 12",
    "or	a4, a4, a5",
    "bgez	t1, 25f",
    // in Loop: Header=BB1_1 Depth=1
    "neg	a4, a4",
    "25:", // .LBB1_7: in Loop: Header=BB1_1 Depth=1
    "lw	a2, 12(sp)", // 4-byte Folded Reload
    "bgez	a4, 26f",
    // in Loop: Header=BB1_1 Depth=1
    "neg	a0, a4",
    "lw	a1, 4(sp)", // 4-byte Folded Reload
    "mulhu	a0, a0, a1",
    "srli	a0, a0, 14",
    "mul	a0, a0, a2",
    "add	a4, a4, a2",
    "add	a4, a4, a0",
    "26:", // .LBB1_9: in Loop: Header=BB1_1 Depth=1
    "mv	a1, a4",
    "lw	a0, 16(sp)", // 4-byte Folded Reload
    "blt	a0, a4, 27f",
    // in Loop: Header=BB1_1 Depth=1
    "lw	a1, 16(sp)", // 4-byte Folded Reload
    "27:", // .LBB1_11: in Loop: Header=BB1_1 Depth=1
    "lw	a0, 8(sp)", // 4-byte Folded Reload
    "mulhu	a0, a1, a0",
    "sub	a1, a1, a1",
    "srli	a0, a0, 14",
    "mul	a0, a0, a2",
    "add	a1, a1, a4",
    "sub	a1, a1, a0",
    "lw	a0, 32(sp)", // 4-byte Folded Reload
    "bge	a0, a1, 28f",
    // in Loop: Header=BB1_1 Depth=1
    "sub	a1, a2, a1",
    "28:", // .LBB1_13: in Loop: Header=BB1_1 Depth=1
    "mv	a3, a1",
    "lw	a0, 28(sp)", // 4-byte Folded Reload
    "blt	a1, a0, 29f",
    // in Loop: Header=BB1_1 Depth=1
    "lw	a0, 32(sp)", // 4-byte Folded Reload
    "sub	a3, a0, a1",
    "29:", // .LBB1_15: in Loop: Header=BB1_1 Depth=1
    "sw	a1, 24(sp)", // 4-byte Folded Spill
    "li	t2, 0",
    "li	s0, 0",
    "slli	a3, a3, 6",
    "srai	a0, a3, 31",
    "sw	a3, 20(sp)", // 4-byte Folded Spill
    "xor	a5, a3, a0",
    "sub	a5, a5, a0",
    "li	a3, 31",
    "li	s1, 1",
    "lui	a1, 2",
    "30:", // .LBB1_16: Parent Loop BB1_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "slli	t2, t2, 1",
    "srl	a0, a5, a3",
    "addi	t1, a1, -1758",
    "sll	a2, s1, a3",
    "addi	a3, a3, -1",
    "andi	a0, a0, 1",
    "or	a0, a0, t2",
    "sltu	a4, t2, t1",
    "addi	a4, a4, -1",
    "and	a2, a2, a4",
    "and	a4, a4, ra",
    "or	s0, s0, a2",
    "add	t2, a4, a0",
    "bne	a3, t0, 30b",
    // in Loop: Header=BB1_1 Depth=1
    "li	a4, 0",
    "li	a5, 0",
    "slli	t2, t2, 12",
    "li	a3, 31",
    "31:", // .LBB1_18: Parent Loop BB1_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "slli	a4, a4, 1",
    "srl	a0, t2, a3",
    "sll	a2, s1, a3",
    "addi	a3, a3, -1",
    "andi	a0, a0, 1",
    "or	a0, a0, a4",
    "sltu	a4, a4, t1",
    "addi	a4, a4, -1",
    "and	a2, a2, a4",
    "and	a4, a4, ra",
    "or	a5, a5, a2",
    "add	a4, a4, a0",
    "bne	a3, t0, 31b",
    // in Loop: Header=BB1_1 Depth=1
    "slli	a3, s0, 12",
    "or	a3, a3, a5",
    "lw	a1, 24(sp)", // 4-byte Folded Reload
    // ERRATA BUG2 patch: lw	a0, 20(sp) (offset=20,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a0, 24(sp)",
    "addi sp, sp, 4",
    "bgez	a0, 32f",
    // in Loop: Header=BB1_1 Depth=1
    "neg	a3, a3",
    "32:", // .LBB1_21: in Loop: Header=BB1_1 Depth=1
    "lui	s1, 1048396",
    "li	t2, 1",
    "srai	a5, a3, 12",
    "li	s0, 63",
    "lui	a4, 1",
    "bge	s0, a5, 33f",
    // in Loop: Header=BB1_1 Depth=1
    "lui	a3, 1",
    "bge	a5, s0, 34f",
    "j	35f",
    "33:", // .LBB1_23: in Loop: Header=BB1_1 Depth=1
    // ERRATA BUG2 patch: slli	a3, a3, 20 (shamt=20)
    "slli a3, a3, 19",
    "slli a3, a3, 1",
    // ERRATA BUG2 patch: srli	a3, a3, 20 (shamt=20)
    "srli a3, a3, 19",
    "srli a3, a3, 1",
    "blt	a5, s0, 35f",
    "34:", // .LBB1_24: in Loop: Header=BB1_1 Depth=1
    "li	a5, 63",
    "35:", // .LBB1_25: in Loop: Header=BB1_1 Depth=1
    "slli	a5, a5, 1",
    "lui	a0, %hi(37f)",
    "addi	a0, a0, %lo(37f)",
    "add	a5, a5, a0",
    "lh	a0, 0(a5)",
    "lh	a2, 2(a5)",
    "sub	a2, a2, a0",
    // --- inline asm begin ---
    "mulh	a5, a2, a3",
    "mul	a2, a2, a3",
    // --- inline asm end ---
    "srli	a2, a2, 12",
    // ERRATA BUG2 patch: slli	a5, a5, 20 (shamt=20)
    "slli a5, a5, 19",
    "slli a5, a5, 1",
    "or	a2, a2, a5",
    "add	a3, a2, a0",
    "lw	a0, 28(sp)", // 4-byte Folded Reload
    "blt	a1, a0, 36f",
    // in Loop: Header=BB1_1 Depth=1
    "neg	a3, a3",
    "36:", // .LBB1_27: in Loop: Header=BB1_1 Depth=1
    "add	a3, a3, a4",
    // --- inline asm begin ---
    "mv	x17, a3",
    // --- inline asm end ---
    "j	22b",
    // --- rodata: cos_table (65 entries, 33 words) ---
    ".p2align 1",
    "37:", // cos_table
    ".word 0x0fff1000", // [0] 4096, 4095
    ".word 0x0ff50ffb", // [4] 4091, 4085
    ".word 0x0fe10fec", // [8] 4076, 4065
    ".word 0x0fc40fd4", // [12] 4052, 4036
    ".word 0x0f9c0fb1", // [16] 4017, 3996
    ".word 0x0f6c0f85", // [20] 3973, 3948
    ".word 0x0f310f50", // [24] 3920, 3889
    ".word 0x0eee0f11", // [28] 3857, 3822
    ".word 0x0ea10ec8", // [32] 3784, 3745
    ".word 0x0e4b0e77", // [36] 3703, 3659
    ".word 0x0dec0e1c", // [40] 3612, 3564
    ".word 0x0d850db9", // [44] 3513, 3461
    ".word 0x0d150d4e", // [48] 3406, 3349
    ".word 0x0c9d0cda", // [52] 3290, 3229
    ".word 0x0c1e0c5e", // [56] 3166, 3102
    ".word 0x0b970bdb", // [60] 3035, 2967
    ".word 0x0b080b50", // [64] 2896, 2824
    ".word 0x0a730abf", // [68] 2751, 2675
    ".word 0x09d80a26", // [72] 2598, 2520
    ".word 0x09370988", // [76] 2440, 2359
    ".word 0x088f08e4", // [80] 2276, 2191
    ".word 0x07e3083a", // [84] 2106, 2019
    ".word 0x0732078b", // [88] 1931, 1842
    ".word 0x067c06d7", // [92] 1751, 1660
    ".word 0x05c2061f", // [96] 1567, 1474
    ".word 0x05050564", // [100] 1380, 1285
    ".word 0x044404a5", // [104] 1189, 1092
    ".word 0x038103e3", // [108] 995, 897
    ".word 0x02bc031f", // [112] 799, 700
    ".word 0x01f50259", // [116] 601, 501
    ".word 0x012d0191", // [120] 401, 301
    ".word 0x006500c9", // [124] 201, 101
    ".word 0x00000000" // [128] 0
);
