// AUTOGENERATED CODE on 2026-02-22T03:16:34.024624 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(colorwheel_bio_code, BM_COLORWHEEL_BIO_START, BM_COLORWHEEL_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	74f",
    // --- inline asm end ---
    "21:", // ws2812c: @ws2812c
    "li	a3, 31",
    "bltu	a3, a0, 26f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 26f",
    "li	t0, 0",
    "22:", // .LBB1_3: =>This Loop Header: Depth=1
    // Child Loop BB1_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "23:", // .LBB1_4: Parent Loop BB1_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 24f",
    // in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	25f",
    "24:", // .LBB1_6: in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "25:", // .LBB1_7: in Loop: Header=BB1_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 23b",
    // in Loop: Header=BB1_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 22b",
    "26:", // .LBB1_9
    "ret",
    "27:", // __udivsi3: @__udivsi3
    "beqz	a1, 29f",
    "mv	t2, a0",
    "li	a4, 0",
    "li	a0, 0",
    "li	a3, 31",
    "li	t0, 1",
    "li	t1, -1",
    "28:", // .LBB2_2: =>This Inner Loop Header: Depth=1
    "slli	a4, a4, 1",
    "srl	a5, t2, a3",
    "sll	a2, t0, a3",
    "addi	a3, a3, -1",
    "andi	a5, a5, 1",
    "or	a4, a4, a5",
    "sltu	a5, a4, a1",
    "addi	a5, a5, -1",
    "and	a2, a2, a5",
    "and	a5, a5, a1",
    "or	a0, a0, a2",
    "sub	a4, a4, a5",
    "bne	a3, t1, 28b",
    "ret",
    "29:", // .LBB2_4
    "li	a0, -1",
    "ret",
    "30:", // __umodsi3: @__umodsi3
    "beqz	a1, 32f",
    "li	a2, 0",
    "li	a3, 31",
    "li	a4, -1",
    "31:", // .LBB3_2: =>This Inner Loop Header: Depth=1
    "slli	a2, a2, 1",
    "srl	a5, a0, a3",
    "andi	a5, a5, 1",
    "or	a2, a2, a5",
    "sltu	a5, a2, a1",
    "addi	a5, a5, -1",
    "and	a5, a5, a1",
    "addi	a3, a3, -1",
    "sub	a2, a2, a5",
    "bne	a3, a4, 31b",
    "j	33f",
    "32:", // .LBB3_3
    "mv	a2, a0",
    "33:", // .LBB3_4
    "mv	a0, a2",
    "ret",
    "34:", // __divsi3: @__divsi3
    "addi	sp, sp, -16",
    "sw	s0, 12(sp)", // 4-byte Folded Spill
    "sw	s1, 8(sp)", // 4-byte Folded Spill
    "mv	t0, a0",
    "beqz	a1, 36f",
    "li	a4, 0",
    "li	a0, 0",
    "srai	t2, t0, 31",
    "srai	s0, a1, 31",
    "li	a3, 31",
    "li	t1, 1",
    "xor	a5, t0, t2",
    "sub	a5, a5, t2",
    "xor	a2, a1, s0",
    "sub	a2, a2, s0",
    "li	t2, -1",
    "35:", // .LBB4_2: =>This Inner Loop Header: Depth=1
    "slli	a4, a4, 1",
    "srl	s0, a5, a3",
    "sll	s1, t1, a3",
    "addi	a3, a3, -1",
    "andi	s0, s0, 1",
    "or	a4, a4, s0",
    "sltu	s0, a4, a2",
    "addi	s0, s0, -1",
    "and	s1, s1, s0",
    "and	s0, s0, a2",
    "or	a0, a0, s1",
    "sub	a4, a4, s0",
    "bne	a3, t2, 35b",
    "j	37f",
    "36:", // .LBB4_3
    "li	a0, -1",
    "37:", // .LBB4_4
    "xor	a1, a1, t0",
    "bgez	a1, 38f",
    "neg	a0, a0",
    "38:", // .LBB4_6
    "lw	s0, 12(sp)", // 4-byte Folded Reload
    "lw	s1, 8(sp)", // 4-byte Folded Reload
    "addi	sp, sp, 16",
    "ret",
    "39:", // __modsi3: @__modsi3
    "srai	a2, a0, 31",
    "xor	a3, a0, a2",
    "sub	a3, a3, a2",
    "beqz	a1, 43f",
    "li	a2, 0",
    "srai	a5, a1, 31",
    "li	a4, 31",
    "xor	a1, a1, a5",
    "sub	a1, a1, a5",
    "li	t0, -1",
    "40:", // .LBB5_2: =>This Inner Loop Header: Depth=1
    "slli	a2, a2, 1",
    "srl	a5, a3, a4",
    "andi	a5, a5, 1",
    "or	a2, a2, a5",
    "sltu	a5, a2, a1",
    "addi	a5, a5, -1",
    "and	a5, a5, a1",
    "addi	a4, a4, -1",
    "sub	a2, a2, a5",
    "bne	a4, t0, 40b",
    "bgez	a0, 42f",
    "41:", // .LBB5_4
    "neg	a2, a2",
    "42:", // .LBB5_5
    "mv	a0, a2",
    "ret",
    "43:", // .LBB5_6
    "mv	a2, a3",
    "bltz	a0, 41b",
    "j	42b",
    "44:", // HsvToRgb: @HsvToRgb
    "slli	a4, a0, 16",
    "srli	a4, a4, 24",
    "srli	a1, a0, 16",
    "beqz	a4, 45f",
    "andi	a2, a0, 255",
    "li	a3, 191",
    "li	t0, 213",
    "andi	a5, a1, 255",
    "mul	a3, a2, a3",
    "xori	a2, a4, 255",
    "mul	a2, a2, a5",
    "srli	a3, a3, 13",
    "srli	t1, a2, 8",
    "mul	a2, a3, t0",
    "add	a0, a0, a2",
    "slli	a2, a0, 1",
    "slli	a0, a0, 3",
    "sub	a0, a0, a2",
    "andi	a0, a0, 254",
    "mul	a2, a0, a4",
    "xori	a0, a0, 255",
    "srli	a2, a2, 8",
    "mul	a0, a0, a4",
    "xori	a2, a2, 255",
    "srli	a0, a0, 8",
    "mul	a2, a2, a5",
    "xori	a4, a0, 255",
    "srli	a0, a2, 8",
    "mul	a5, a4, a5",
    "li	a2, 1",
    "srli	a5, a5, 8",
    "bge	a2, a3, 46f",
    "li	a2, 2",
    "beq	a3, a2, 47f",
    "li	a2, 3",
    "beq	a3, a2, 48f",
    "li	a2, 4",
    "bne	a3, a2, 52f",
    "mv	a3, a5",
    "mv	a4, t1",
    "j	49f",
    "45:", // .LBB6_6
    "mv	a3, a1",
    "mv	a4, a1",
    "j	49f",
    "46:", // .LBB6_7
    "beqz	a3, 50f",
    "li	a2, 1",
    "bne	a3, a2, 52f",
    "mv	a3, a0",
    "mv	a4, a1",
    "j	51f",
    "47:", // .LBB6_10
    "mv	a3, t1",
    "mv	a4, a1",
    "mv	a0, a5",
    "j	53f",
    "48:", // .LBB6_11
    "mv	a3, t1",
    "mv	a4, a0",
    "49:", // .LBB6_12
    "mv	a0, a1",
    "j	53f",
    "50:", // .LBB6_13
    "mv	a3, a1",
    "mv	a4, a5",
    "51:", // .LBB6_14
    "mv	a0, t1",
    "j	53f",
    "52:", // .LBB6_15
    "mv	a3, a1",
    "mv	a4, t1",
    "53:", // .LBB6_16
    "slli	a0, a0, 24",
    "slli	a4, a4, 24",
    "srli	a0, a0, 8",
    "srli	a4, a4, 16",
    "andi	a1, a3, 255",
    "or	a1, a1, a4",
    "or	a0, a0, a1",
    "ret",
    "54:", // RgbToHsv: @RgbToHsv
    "addi	sp, sp, -32",
    "sw	ra, 28(sp)", // 4-byte Folded Spill
    "sw	s0, 24(sp)", // 4-byte Folded Spill
    "sw	s1, 20(sp)", // 4-byte Folded Spill
    "srli	a1, a0, 16",
    "andi	s0, a0, 255",
    "slli	a0, a0, 16",
    "srli	s1, a0, 24",
    "sw	a1, 12(sp)", // 4-byte Folded Spill
    "andi	a2, a1, 255",
    "mv	a0, s0",
    "bgeu	s0, s1, 57f",
    "bgeu	a0, a2, 58f",
    "55:", // .LBB7_2
    "bgeu	s1, s0, 59f",
    "56:", // .LBB7_3
    "mv	a1, s0",
    "bltu	a2, s0, 61f",
    "mv	a1, a2",
    "j	61f",
    "57:", // .LBB7_5
    "mv	a0, s1",
    "bltu	s1, a2, 55b",
    "58:", // .LBB7_6
    "mv	a0, a2",
    "bltu	s1, s0, 56b",
    "59:", // .LBB7_7
    "mv	a1, s1",
    "bltu	a2, s1, 60f",
    "mv	a1, a2",
    "60:", // .LBB7_9
    "beqz	a1, 64f",
    "61:", // .LBB7_10
    "sw	a1, 16(sp)", // 4-byte Folded Spill
    "sub	a0, a1, a0",
    "sw	a0, 8(sp)", // 4-byte Folded Spill
    "jal	ra, 34b",
    "andi	a1, a0, 255",
    "beqz	a1, 62f",
    "neg	a0, a0",
    "sw	a0, 4(sp)", // 4-byte Folded Spill
    "lw	a0, 16(sp)", // 4-byte Folded Reload
    "bne	a0, s0, 63f",
    "lbu	a0, 12(sp)", // 4-byte Folded Reload
    "sub	s1, s1, a0",
    "lui	a0, 688",
    "mul	a0, s1, a0",
    "srai	a0, a0, 16",
    "lw	a1, 8(sp)", // 4-byte Folded Reload
    "jal	ra, 34b",
    "slli	a0, a0, 16",
    "srli	a0, a0, 16",
    "j	66f",
    "62:", // .LBB7_13
    "li	a0, 0",
    "j	67f",
    "63:", // .LBB7_14
    "bne	a0, s1, 65f",
    "lbu	a0, 12(sp)", // 4-byte Folded Reload
    "sub	a0, a0, s0",
    "lui	a1, 688",
    "mul	a0, a0, a1",
    "srai	a0, a0, 16",
    "lw	a1, 8(sp)", // 4-byte Folded Reload
    "jal	ra, 34b",
    "slli	a0, a0, 16",
    "srli	a0, a0, 16",
    "addi	a0, a0, 85",
    "j	66f",
    "64:", // .LBB7_16
    "li	a2, 0",
    "li	a0, 0",
    "j	68f",
    "65:", // .LBB7_17
    "sub	s0, s0, s1",
    "lui	a0, 688",
    "mul	a0, s0, a0",
    "srai	a0, a0, 16",
    "lw	a1, 8(sp)", // 4-byte Folded Reload
    "jal	ra, 34b",
    "slli	a0, a0, 16",
    "srli	a0, a0, 16",
    "addi	a0, a0, 171",
    "66:", // .LBB7_18
    "andi	a0, a0, 255",
    "lbu	a1, 4(sp)", // 4-byte Folded Reload
    "slli	a1, a1, 8",
    "67:", // .LBB7_19
    "lw	a2, 16(sp)", // 4-byte Folded Reload
    "68:", // .LBB7_20
    "slli	a2, a2, 16",
    "or	a0, a0, a1",
    "or	a0, a0, a2",
    "lw	ra, 28(sp)", // 4-byte Folded Reload
    "lw	s0, 24(sp)", // 4-byte Folded Reload
    // ERRATA BUG2 patch: lw	s1, 20(sp) (offset=20,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw s1, 24(sp)",
    "addi sp, sp, 4",
    "addi	sp, sp, 32",
    "ret",
    "69:", // rainbow_update: @rainbow_update
    "addi	sp, sp, -32",
    "sw	ra, 28(sp)", // 4-byte Folded Spill
    "sw	s0, 24(sp)", // 4-byte Folded Spill
    "sw	s1, 20(sp)", // 4-byte Folded Spill
    "sw	a1, 8(sp)", // 4-byte Folded Spill
    "li	a1, 100",
    "mv	s1, a0",
    "mv	s0, a0",
    "bltu	a0, a1, 70f",
    "li	s0, 100",
    "70:", // .LBB8_2
    "li	a0, 256",
    "mv	a1, s0",
    "jal	ra, 27b",
    "beqz	s1, 73f",
    "li	a1, 0",
    "lui	a3, %hi(77f)",
    "slli	a4, s0, 1",
    "lw	a2, %lo(77f)(a3)",
    "addi	a3, a3, %lo(77f)",
    "mv	t0, s0",
    "add	a4, a4, s0",
    "addi	a3, a3, 6",
    "add	a4, a4, a3",
    "li	a5, 200",
    "li	s1, 64",
    "71:", // .LBB8_4: =>This Inner Loop Header: Depth=1
    "mul	s0, a1, a0",
    "add	s0, s0, a2",
    "sb	s0, -2(a3)",
    "sb	a5, -1(a3)",
    "sb	s1, 0(a3)",
    "addi	a3, a3, 3",
    "addi	a1, a1, 1",
    "bne	a3, a4, 71b",
    "slli	a0, t0, 2",
    "lui	s1, %hi(77f)",
    "addi	s1, s1, %lo(77f)",
    "addi	s0, s1, 304",
    "addi	s1, s1, 4",
    "add	a0, a0, s0",
    "sw	a0, 12(sp)", // 4-byte Folded Spill
    // implicit-def: $x10
    // kill: killed $x10
    "72:", // .LBB8_6: =>This Inner Loop Header: Depth=1
    "lbu	a0, 1(s1)",
    "lbu	a1, 0(s1)",
    "lbu	a2, 2(s1)",
    "slli	a0, a0, 8",
    "or	a0, a0, a1",
    "lui	a1, 1044480",
    "lw	a3, 16(sp)", // 4-byte Folded Reload
    "and	a1, a1, a3",
    "slli	a2, a2, 16",
    "or	a1, a1, a2",
    "or	a0, a0, a1",
    "sw	a0, 16(sp)", // 4-byte Folded Spill
    "jal	ra, 44b",
    "srli	a1, a0, 16",
    "slli	a0, a0, 16",
    "srli	a0, a0, 8",
    "or	a0, a0, a1",
    "sw	a0, 0(s0)",
    "addi	s0, s0, 4",
    "addi	s1, s1, 3",
    "lw	a0, 12(sp)", // 4-byte Folded Reload
    "bne	s0, a0, 72b",
    "73:", // .LBB8_7
    "lui	a0, %hi(77f)",
    "lw	a1, %lo(77f)(a0)",
    "lw	a2, 8(sp)", // 4-byte Folded Reload
    "add	a1, a1, a2",
    "andi	a1, a1, 255",
    "sw	a1, %lo(77f)(a0)",
    "lw	ra, 28(sp)", // 4-byte Folded Reload
    "lw	s0, 24(sp)", // 4-byte Folded Reload
    // ERRATA BUG2 patch: lw	s1, 20(sp) (offset=20,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw s1, 24(sp)",
    "addi sp, sp, 4",
    "addi	sp, sp, 32",
    "ret",
    "74:", // main: @main
    "addi	sp, sp, -32",
    "sw	ra, 28(sp)", // 4-byte Folded Spill
    "sw	s0, 24(sp)", // 4-byte Folded Spill
    "sw	s1, 20(sp)", // 4-byte Folded Spill
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "sw	a0, 16(sp)", // 4-byte Folded Spill
    // --- inline asm begin ---
    "mv	s1, x17",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "sw	a0, 12(sp)", // 4-byte Folded Spill
    "lui	a0, 24",
    "addi	s0, a0, 1696",
    "75:", // .LBB9_1: =>This Loop Header: Depth=1
    // Child Loop BB9_2 Depth 2
    "lw	a0, 16(sp)", // 4-byte Folded Reload
    "lui	a1, %hi(79f)",
    "addi	a1, a1, %lo(79f)",
    "mv	a2, s1",
    "jal	ra, 21b",
    "mv	a0, s1",
    "lw	a1, 12(sp)", // 4-byte Folded Reload
    "jal	ra, 69b",
    "mv	a0, s0",
    "76:", // .LBB9_2: Parent Loop BB9_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a0, a0, -1",
    "bnez	a0, 76b",
    "j	75b",
    // --- rodata: .L_MergedGlobals (4 entries, 1 words) ---
    ".p2align 2",
    "77:", // .L_MergedGlobals
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: render_buf (300 entries, 75 words) ---
    ".p2align 0",
    "78:", // render_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000", // [36] 0, 0, 0, 0
    ".word 0x00000000", // [40] 0, 0, 0, 0
    ".word 0x00000000", // [44] 0, 0, 0, 0
    ".word 0x00000000", // [48] 0, 0, 0, 0
    ".word 0x00000000", // [52] 0, 0, 0, 0
    ".word 0x00000000", // [56] 0, 0, 0, 0
    ".word 0x00000000", // [60] 0, 0, 0, 0
    ".word 0x00000000", // [64] 0, 0, 0, 0
    ".word 0x00000000", // [68] 0, 0, 0, 0
    ".word 0x00000000", // [72] 0, 0, 0, 0
    ".word 0x00000000", // [76] 0, 0, 0, 0
    ".word 0x00000000", // [80] 0, 0, 0, 0
    ".word 0x00000000", // [84] 0, 0, 0, 0
    ".word 0x00000000", // [88] 0, 0, 0, 0
    ".word 0x00000000", // [92] 0, 0, 0, 0
    ".word 0x00000000", // [96] 0, 0, 0, 0
    ".word 0x00000000", // [100] 0, 0, 0, 0
    ".word 0x00000000", // [104] 0, 0, 0, 0
    ".word 0x00000000", // [108] 0, 0, 0, 0
    ".word 0x00000000", // [112] 0, 0, 0, 0
    ".word 0x00000000", // [116] 0, 0, 0, 0
    ".word 0x00000000", // [120] 0, 0, 0, 0
    ".word 0x00000000", // [124] 0, 0, 0, 0
    ".word 0x00000000", // [128] 0, 0, 0, 0
    ".word 0x00000000", // [132] 0, 0, 0, 0
    ".word 0x00000000", // [136] 0, 0, 0, 0
    ".word 0x00000000", // [140] 0, 0, 0, 0
    ".word 0x00000000", // [144] 0, 0, 0, 0
    ".word 0x00000000", // [148] 0, 0, 0, 0
    ".word 0x00000000", // [152] 0, 0, 0, 0
    ".word 0x00000000", // [156] 0, 0, 0, 0
    ".word 0x00000000", // [160] 0, 0, 0, 0
    ".word 0x00000000", // [164] 0, 0, 0, 0
    ".word 0x00000000", // [168] 0, 0, 0, 0
    ".word 0x00000000", // [172] 0, 0, 0, 0
    ".word 0x00000000", // [176] 0, 0, 0, 0
    ".word 0x00000000", // [180] 0, 0, 0, 0
    ".word 0x00000000", // [184] 0, 0, 0, 0
    ".word 0x00000000", // [188] 0, 0, 0, 0
    ".word 0x00000000", // [192] 0, 0, 0, 0
    ".word 0x00000000", // [196] 0, 0, 0, 0
    ".word 0x00000000", // [200] 0, 0, 0, 0
    ".word 0x00000000", // [204] 0, 0, 0, 0
    ".word 0x00000000", // [208] 0, 0, 0, 0
    ".word 0x00000000", // [212] 0, 0, 0, 0
    ".word 0x00000000", // [216] 0, 0, 0, 0
    ".word 0x00000000", // [220] 0, 0, 0, 0
    ".word 0x00000000", // [224] 0, 0, 0, 0
    ".word 0x00000000", // [228] 0, 0, 0, 0
    ".word 0x00000000", // [232] 0, 0, 0, 0
    ".word 0x00000000", // [236] 0, 0, 0, 0
    ".word 0x00000000", // [240] 0, 0, 0, 0
    ".word 0x00000000", // [244] 0, 0, 0, 0
    ".word 0x00000000", // [248] 0, 0, 0, 0
    ".word 0x00000000", // [252] 0, 0, 0, 0
    ".word 0x00000000", // [256] 0, 0, 0, 0
    ".word 0x00000000", // [260] 0, 0, 0, 0
    ".word 0x00000000", // [264] 0, 0, 0, 0
    ".word 0x00000000", // [268] 0, 0, 0, 0
    ".word 0x00000000", // [272] 0, 0, 0, 0
    ".word 0x00000000", // [276] 0, 0, 0, 0
    ".word 0x00000000", // [280] 0, 0, 0, 0
    ".word 0x00000000", // [284] 0, 0, 0, 0
    ".word 0x00000000", // [288] 0, 0, 0, 0
    ".word 0x00000000", // [292] 0, 0, 0, 0
    ".word 0x00000000", // [296] 0, 0, 0, 0
    // --- rodata: led_buf (400 entries, 100 words) ---
    ".p2align 0",
    "79:", // led_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000", // [36] 0, 0, 0, 0
    ".word 0x00000000", // [40] 0, 0, 0, 0
    ".word 0x00000000", // [44] 0, 0, 0, 0
    ".word 0x00000000", // [48] 0, 0, 0, 0
    ".word 0x00000000", // [52] 0, 0, 0, 0
    ".word 0x00000000", // [56] 0, 0, 0, 0
    ".word 0x00000000", // [60] 0, 0, 0, 0
    ".word 0x00000000", // [64] 0, 0, 0, 0
    ".word 0x00000000", // [68] 0, 0, 0, 0
    ".word 0x00000000", // [72] 0, 0, 0, 0
    ".word 0x00000000", // [76] 0, 0, 0, 0
    ".word 0x00000000", // [80] 0, 0, 0, 0
    ".word 0x00000000", // [84] 0, 0, 0, 0
    ".word 0x00000000", // [88] 0, 0, 0, 0
    ".word 0x00000000", // [92] 0, 0, 0, 0
    ".word 0x00000000", // [96] 0, 0, 0, 0
    ".word 0x00000000", // [100] 0, 0, 0, 0
    ".word 0x00000000", // [104] 0, 0, 0, 0
    ".word 0x00000000", // [108] 0, 0, 0, 0
    ".word 0x00000000", // [112] 0, 0, 0, 0
    ".word 0x00000000", // [116] 0, 0, 0, 0
    ".word 0x00000000", // [120] 0, 0, 0, 0
    ".word 0x00000000", // [124] 0, 0, 0, 0
    ".word 0x00000000", // [128] 0, 0, 0, 0
    ".word 0x00000000", // [132] 0, 0, 0, 0
    ".word 0x00000000", // [136] 0, 0, 0, 0
    ".word 0x00000000", // [140] 0, 0, 0, 0
    ".word 0x00000000", // [144] 0, 0, 0, 0
    ".word 0x00000000", // [148] 0, 0, 0, 0
    ".word 0x00000000", // [152] 0, 0, 0, 0
    ".word 0x00000000", // [156] 0, 0, 0, 0
    ".word 0x00000000", // [160] 0, 0, 0, 0
    ".word 0x00000000", // [164] 0, 0, 0, 0
    ".word 0x00000000", // [168] 0, 0, 0, 0
    ".word 0x00000000", // [172] 0, 0, 0, 0
    ".word 0x00000000", // [176] 0, 0, 0, 0
    ".word 0x00000000", // [180] 0, 0, 0, 0
    ".word 0x00000000", // [184] 0, 0, 0, 0
    ".word 0x00000000", // [188] 0, 0, 0, 0
    ".word 0x00000000", // [192] 0, 0, 0, 0
    ".word 0x00000000", // [196] 0, 0, 0, 0
    ".word 0x00000000", // [200] 0, 0, 0, 0
    ".word 0x00000000", // [204] 0, 0, 0, 0
    ".word 0x00000000", // [208] 0, 0, 0, 0
    ".word 0x00000000", // [212] 0, 0, 0, 0
    ".word 0x00000000", // [216] 0, 0, 0, 0
    ".word 0x00000000", // [220] 0, 0, 0, 0
    ".word 0x00000000", // [224] 0, 0, 0, 0
    ".word 0x00000000", // [228] 0, 0, 0, 0
    ".word 0x00000000", // [232] 0, 0, 0, 0
    ".word 0x00000000", // [236] 0, 0, 0, 0
    ".word 0x00000000", // [240] 0, 0, 0, 0
    ".word 0x00000000", // [244] 0, 0, 0, 0
    ".word 0x00000000", // [248] 0, 0, 0, 0
    ".word 0x00000000", // [252] 0, 0, 0, 0
    ".word 0x00000000", // [256] 0, 0, 0, 0
    ".word 0x00000000", // [260] 0, 0, 0, 0
    ".word 0x00000000", // [264] 0, 0, 0, 0
    ".word 0x00000000", // [268] 0, 0, 0, 0
    ".word 0x00000000", // [272] 0, 0, 0, 0
    ".word 0x00000000", // [276] 0, 0, 0, 0
    ".word 0x00000000", // [280] 0, 0, 0, 0
    ".word 0x00000000", // [284] 0, 0, 0, 0
    ".word 0x00000000", // [288] 0, 0, 0, 0
    ".word 0x00000000", // [292] 0, 0, 0, 0
    ".word 0x00000000", // [296] 0, 0, 0, 0
    ".word 0x00000000", // [300] 0, 0, 0, 0
    ".word 0x00000000", // [304] 0, 0, 0, 0
    ".word 0x00000000", // [308] 0, 0, 0, 0
    ".word 0x00000000", // [312] 0, 0, 0, 0
    ".word 0x00000000", // [316] 0, 0, 0, 0
    ".word 0x00000000", // [320] 0, 0, 0, 0
    ".word 0x00000000", // [324] 0, 0, 0, 0
    ".word 0x00000000", // [328] 0, 0, 0, 0
    ".word 0x00000000", // [332] 0, 0, 0, 0
    ".word 0x00000000", // [336] 0, 0, 0, 0
    ".word 0x00000000", // [340] 0, 0, 0, 0
    ".word 0x00000000", // [344] 0, 0, 0, 0
    ".word 0x00000000", // [348] 0, 0, 0, 0
    ".word 0x00000000", // [352] 0, 0, 0, 0
    ".word 0x00000000", // [356] 0, 0, 0, 0
    ".word 0x00000000", // [360] 0, 0, 0, 0
    ".word 0x00000000", // [364] 0, 0, 0, 0
    ".word 0x00000000", // [368] 0, 0, 0, 0
    ".word 0x00000000", // [372] 0, 0, 0, 0
    ".word 0x00000000", // [376] 0, 0, 0, 0
    ".word 0x00000000", // [380] 0, 0, 0, 0
    ".word 0x00000000", // [384] 0, 0, 0, 0
    ".word 0x00000000", // [388] 0, 0, 0, 0
    ".word 0x00000000", // [392] 0, 0, 0, 0
    ".word 0x00000000" // [396] 0, 0, 0, 0
);
