/*
 * fp_q16.h - Fixed-point math library
 *
 * Format: configurable Q format via FP_FRAC_BITS
 * Default: Q16.16 (16 integer bits, 16 fractional bits)
 *
 * Representation: signed 32-bit integer
 * Range (Q16.16): -32768.0 to +32767.99999
 * Resolution:      1/65536 ~= 0.0000153
 *
 * Cosine is computed via CORDIC (rotation mode, 16 iterations) rather than
 * a lookup table.  Effective precision is ~15 ulp, substantially better than
 * the 64-entry table used in the Q12 version.
 */

#ifndef FP_H
#define FP_H

#include <stdint.h>
#include <stddef.h>

/* --- Configuration --- */

#ifndef FP_FRAC_BITS
#define FP_FRAC_BITS 16
#endif

#define FP_ONE  (1 << FP_FRAC_BITS)
#define FP_MASK (FP_ONE - 1)

typedef int32_t fp_t;

/* --- Constants ---
 *
 * All computed at compile time from integer literals.
 *
 * At Q16 (FP_ONE = 65536):
 *   PI      = round(3.14159265358979 * 65536) = 205887
 *   TWO_PI  = 411775
 *   HALF_PI = 102944
 */
#define FP_PI      ((fp_t)(3.14159265358979f * FP_ONE + 0.5f))
#define FP_TWO_PI  ((fp_t)(6.28318530717959f * FP_ONE + 0.5f))
#define FP_HALF_PI ((fp_t)(1.57079632679490f * FP_ONE + 0.5f))

/* --- Conversion --- */

#define FP_FROM_INT(x)   ((fp_t)((x) << FP_FRAC_BITS))
#define FP_TO_INT(x)     ((int32_t)((x) >> FP_FRAC_BITS))
#define FP_FROM_FLOAT(x) ((fp_t)((x) * FP_ONE + 0.5f))
#define FP_TO_FLOAT(x)   ((float)(x) / FP_ONE)

#define FIX16_OVERFLOW    0x80000000
#define FIX16_MAXIMUM  0x7FFFFFFF /*!< the maximum value of fp_t */
#define FIX16_MINIMUM  0x80000000 /*!< the minimum value of fp_t */

/* --- Arithmetic --- */

static inline fp_t fp_add(fp_t a, fp_t b)
{
	return a + b;
}

static inline fp_t fp_sub(fp_t a, fp_t b)
{
	return a - b;
}

/* Saturating arithmetic */
static inline fp_t fp_sadd(fp_t a, fp_t b)
{
	fp_t result = fp_add(a, b);

	if (result == (fp_t) FIX16_OVERFLOW)
		return (a >= 0) ? FIX16_MAXIMUM : FIX16_MINIMUM;

	return result;
}

static inline fp_t fp_ssub(fp_t a, fp_t b)
{
	fp_t result = fp_sub(a, b);

	if (result == (fp_t) FIX16_OVERFLOW)
		return (a >= 0) ? FIX16_MAXIMUM : FIX16_MINIMUM;

	return result;
}

/*
 * fp_mul - fixed-point multiply using RISC-V mulh/mul pair.
 *
 * Reconstructs the full 64-bit product from the high (mulh) and low (mul)
 * 32-bit words, then shifts right by FP_FRAC_BITS to re-align the binary
 * point.  The early-clobber on 'hi' (&) prevents the compiler from aliasing
 * it with an input register.
 */

static inline fp_t fp_mul(fp_t a, fp_t b)
{
    int64_t result = (int64_t)a * (int64_t)b;
    return (fp_t)(result >> FP_FRAC_BITS);
}

fp_t fp_div(fp_t a, fp_t b)
{
	// This uses the basic binary restoring division algorithm.
	// It appears to be faster to do the whole division manually than
	// trying to compose a 64-bit divide out of 32-bit divisions on
	// platforms without hardware divide.

	if (b == 0)
		return FIX16_MINIMUM;

	uint32_t remainder = (a >= 0) ? a : (-a);
	uint32_t divider = (b >= 0) ? b : (-b);

	uint32_t quotient = 0;
	uint32_t bit = 0x10000;

	/* The algorithm requires D >= R */
	while (divider < remainder)
	{
		divider <<= 1;
		bit <<= 1;
	}

	//if (!bit)
	//	return FIX16_OVERFLOW;

	if (divider & 0x80000000)
	{
		// Perform one step manually to avoid overflows later.
		// We know that divider's bottom bit is 0 here.
		if (remainder >= divider)
		{
				quotient |= bit;
				remainder -= divider;
		}
		divider >>= 1;
		bit >>= 1;
	}

	/* Main division loop */
	while (bit && remainder)
	{
		if (remainder >= divider)
		{
				quotient |= bit;
				remainder -= divider;
		}

		remainder <<= 1;
		bit >>= 1;
	}

	if (remainder >= divider)
	{
		quotient++;
	}

	fp_t result = quotient;

	/* Figure out the sign of result */
	if ((a ^ b) & 0x80000000)
	{
		result = -result;
	}

	return result;
}

/* --- CORDIC cosine --- */

/*
 * CORDIC rotation-mode overview
 * ==============================
 * At each step i (0 .. N-1) we rotate a 2-D vector (x, y) by ±atan(2^-i):
 *
 *   x' = x - d * (y >> i)
 *   y' = y + d * (x >> i)      d = +1 if remaining angle > 0, else -1
 *   z' = z - d * atan_table[i]
 *
 * Starting with (x,y,z) = (K, 0, target_angle), after N iterations:
 *   x  ≈  cos(target_angle)   (in Q16, scaled by FP_ONE)
 *   y  ≈  sin(target_angle)
 *
 * where K = 1 / prod_{i=0}^{N-1} sqrt(1 + 2^{-2i}) is the CORDIC gain
 * pre-applied to the initial x so the output is already unit-scaled.
 *
 * Number of iterations
 * --------------------
 * 16 iterations give ~16 bits of precision, matching FP_FRAC_BITS = 16.
 * Each iteration adds roughly one bit of accuracy.
 *
 * atan table (Q16)
 * ----------------
 * atan_table[i] = round( atan(2^-i) * 65536 )
 *
 * Generated by:
 *   import math
 *   Q = 65536
 *   [round(math.atan(2**-i) * Q) for i in range(16)]
 *
 *   i=0:  atan(1)      = 0.7853982 -> 51472
 *   i=1:  atan(0.5)    = 0.4636476 -> 30386
 *   i=2:  atan(0.25)   = 0.2449787 -> 16055
 *   i=3:  atan(0.125)  = 0.1243550 ->  8150
 *   ...
 *
 * CORDIC gain K (Q16)
 * --------------------
 * K = prod_{i=0}^{15} 1/sqrt(1 + 2^{-2i})  ~= 0.60725293500888
 * K_Q16 = round(0.60725293500888 * 65536)   = 39797
 */

#define CORDIC_ITERATIONS 16

static const int32_t cordic_atan_table[CORDIC_ITERATIONS] = {
    51472, 30386, 16055, 8150, 4091, 2047, 1024, 512,
    256,   128,   64,    32,   16,   8,    4,    2
};

/*
 * CORDIC gain K in Q16.
 *
 * K = 1 / prod_{i=0}^{15} sqrt(1 + 2^{-2i})
 *   = 0.6072529350088812561...
 * round(K * 65536) = 39797
 *
 * We start the CORDIC vector at (K_Q16, 0) so that the output x is already
 * in Q16 with magnitude cos(angle), no post-multiply needed.
 */
#define CORDIC_K_Q16  ((int32_t)39797)

/*
 * fp_cos_cordic - internal CORDIC rotation for angle in [0, pi/2].
 *
 * Input:  angle in Q16, must be in [0, FP_HALF_PI].
 * Output: cos(angle) in Q16.
 *
 * The initial vector is (K, 0) with K pre-scaled by FP_ONE so all
 * arithmetic stays in integer Q16 throughout.
 */
static inline fp_t fp_cos_cordic(fp_t angle)
{
    int32_t x = CORDIC_K_Q16;
    int32_t y = 0;
    int32_t z = angle;
    int     i;

    for (i = 0; i < CORDIC_ITERATIONS; i++) {
        int32_t dx = y >> i;
        int32_t dy = x >> i;
        if (z >= 0) {
            /* Rotate counter-clockwise: subtract angle step */
            x -= dx;
            y += dy;
            z -= cordic_atan_table[i];
        } else {
            /* Rotate clockwise: add angle step */
            x += dx;
            y -= dy;
            z += cordic_atan_table[i];
        }
    }

    return (fp_t)x;
}

/*
 * fp_cos - cosine of x (angle in Q16 radians).
 *
 * Symmetry used to cover the full circle from [0, pi/2]:
 *   [0,     pi/2]:  cos(x)        -> CORDIC direct
 *   [pi/2,  pi]:    cos(pi - x)   -> CORDIC, result negated
 *   [pi,  3pi/2]:   cos(x - pi)   -> same as [0, pi/2] by symmetry, negated
 *   [3pi/2, 2pi]:   cos(2pi - x)  -> CORDIC direct
 *
 * Range reduction for large magnitudes uses integer period counting
 * (one division by 2*pi) to avoid slow repeated subtraction loops.
 */
static inline fp_t fp_cos(fp_t x)
{
    int32_t negate = 0;

    /* --- Range-reduce to [0, 2*pi) --- */
    if (x < 0) {
        /* cos is even: cos(-x) = cos(x) */
        x = -x;
    }
    if (x >= FP_TWO_PI) {
        /* Integer number of full periods to subtract.
         * fp_div is used here; for performance-critical paths the caller
         * should pre-reduce the angle. */
        int32_t periods = FP_TO_INT(fp_div(x, FP_TWO_PI));
        // x -= (fp_t)(periods * FP_TWO_PI);
		x = fp_sub( x, fp_mul(
			FP_FROM_INT(periods), FP_TWO_PI )
		);
        /* Guard against rounding pushing x under 0 */
        if (x < 0)
		   x = fp_add(x, FP_TWO_PI);
    }

    /* --- Quadrant reduction to [0, pi/2] --- */

    /* [pi, 2pi] -> [0, pi]:  cos(2pi - x) = cos(x) */
    if (x > FP_PI) {
        x = FP_TWO_PI - x;
    }

    /* [pi/2, pi] -> [0, pi/2]:  cos(pi - x) = -cos(x) */
    if (x > FP_HALF_PI) {
        x      = FP_PI - x;
        negate = 1;
    }

    /* --- CORDIC in [0, pi/2] --- */
    fp_t result = fp_cos_cordic(x);

    return negate ? -result : result;
}

#endif /* FP_H */