[package]
name = "cramium-emu"
version = "0.1.0"
edition = "2021"

[dependencies]
xous = "0.9.65"
xous-ipc = "0.10.5"
xous-names = { package = "xous-api-names", version = "0.9.66" }
"ux-api" = { path = "../../libs/ux-api" }
"rand" = "0.8"
rand_core = "0.6.4"
log = "0.4.14"
log-server = { package = "xous-api-log", version = "0.1.64" }
num-derive = { version = "0.4.2", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
rkyv = { version = "0.8.8", default-features = false, features = [
    "std",
    "alloc",
] }
cramium-api = { path = "../../libs/cramium-api", features = [
    "derive-rkyv",
    "std",
] }

[target.'cfg(any(windows,unix))'.dependencies]
minifb = "0.26.0"

[features]
hosted-baosec = []
default = ["hosted-baosec"]
