[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "IME front end"
edition = "2018"
name = "ime-frontend"
version = "0.1.0"

# Dependency versions enforced by Cargo.lock.
[dependencies]
gam = { path = "../gam" }
ux-api = { path = "../../libs/ux-api" }
ime-plugin-api = { path = "../ime-plugin-api" }
keyboard = { path = "../keyboard" }
log = "0.4.14"
log-server = { package = "xous-api-log", version = "0.1.64" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.64" }
xous = "0.9.65"
locales = { path = "../../locales" }
xous-ipc = "0.10.5"
xous-names = { package = "xous-api-names", version = "0.9.66" }

num-derive = { version = "0.4.2", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
rkyv = { version = "0.8.8", default-features = false, features = [
    "std",
    "alloc",
] }

tts-frontend = { path = "../tts" }

utralib = { version = "0.1.25", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
tts = []
debugprint = []
default = []                      # "debugprint"
