#!/usr/bin/env bash

if ! hash tmux 2>/dev/null; then
	echo "Install tmux first..."
	exit 1
fi

function has-session {
	tmux has-session -t $1 2>/dev/null
}

function get-shell {
	getent passwd $USER | awk -F: '{ print $7 }'
}

if [ "$1" == "kill" ]; then
	echo "Killing tmux"
	tmux kill-server
	exit 0
fi


SESSION_NAME="zcssr"
SHELL="`get-shell`"
echo $SHELL
if has-session $SESSION_NAME ; then
	echo "Session $SESSION_NAME already exists"
else
        echo "Creating new session $SESSION_NAME"
        tmux new-session -d -s $SESSION_NAME -n $SESSION_NAME
        tmux split-window -h
        tmux select-pane -t 0
        tmux split-window -h
        tmux select-pane -t 0
        tmux split-window -v -p 20
        tmux select-pane -t 2
        tmux split-window -v -p 20
        tmux select-pane -t 4

        #+-----------------------+
        #| watch |watch  | shell |
        #|       |       |       |
        #|-------|-------|       |
        #| watch | open  |       |
        #|  itm  | ocd   |       |
        #+-----------------------+

        tmux send-keys -t $SESSION_NAME.0 cd\ usb_bootloader Enter ./watch Enter

        tmux send-keys -t $SESSION_NAME.1 cd\ usb_bootloader Enter ./monitor_itm Enter
        
        tmux send-keys -t $SESSION_NAME.2 cd\ usbd_mass_storage Enter ./test Enter

        tmux send-keys -t $SESSION_NAME.3 cd\ usb_bootloader Enter ./run_openocd Enter

        tmux send-keys -t $SESSION_NAME.4 cd\ usb_bootloader Enter ./release
fi 

tmux attach-session -d -t $SESSION_NAME
