// This file is autogenerated by xous-core/loader/src/generate_fonts.py. Do not edit.
// The order of these modules impacts the link order, which changes the position in the binary image.
pub mod hanzi;
pub mod emoji;
pub mod regular;
pub mod small;
pub mod bold;
