#![cfg_attr(rustfmt, rustfmt_skip)]
// DO NOT MAKE EDITS HERE because this file is automatically generated.
// The order of these modules affects the link order in the loader, which is referred to in the graphics engine.
// To make changes, see <xous_root>/libs/blitstr2/codegen/main.go

#[cfg(not(feature = "bao1x"))]
pub mod emoji;
#[cfg(not(feature = "bao1x"))]
pub mod zh;
#[cfg(not(feature = "bao1x"))]
pub mod ja;
#[cfg(not(feature = "bao1x"))]
pub mod kr;
#[cfg(not(feature = "bao1x"))]
pub mod bold;
#[cfg(not(feature = "bao1x"))]
pub mod mono;
#[cfg(not(feature = "bao1x"))]
pub mod regular;
#[cfg(not(feature = "bao1x"))]
pub mod tall;
#[cfg(not(feature = "bao1x"))]
pub mod small;
