[alias]
xtask = "run --package xtask --"

# [net]
# offline = true              # do not access the network

[build]
rustflags = ["--cfg", "crossbeam_no_atomic_64"]

# [target.riscv32imac-unknown-xous-elf]
# linker = "/usr/bin/mold"
# rustflags = [
#     "-C", "linker-flavor=ld",
#     "-C", "relocation-model=pic",
#     "-C", "link-arg=-shared",
#     "--cfg", "crossbeam_no_atomic_64"
#     ]

[target.riscv32imac-unknown-xous-elf]
rustflags = ["--cfg", 'curve25519_dalek_backend="u32e_backend"']

[target.riscv32imac-unknown-none-elf]
rustflags = ["--cfg", 'curve25519_dalek_backend="fiat"']
