// ===================== DATA SLOT MAP =====================
// Below is testing code generated by Claude Opus 4.8-high to make sure there are no collisions
// in the data slot map. The idea is to have a build-time check that makes sure everything is consistent.
//
// Companion to `owc_slot_map.rs`, for the RRAM data slots. Two things make this different
// from the one-way counter map:
//
//   1. Intentional aliases. `ERASE_PROOF` deliberately occupies the last slot of the `CHAFF_KEYS` range (see
//      the comment on the constant). A plain "no two claims share a slot" rule would reject a correct map, so
//      claims are tagged Primary or Alias: at most one Primary owns a slot, and every Alias slot must fall
//      inside some Primary. An alias floating in unclaimed space is an error; an undeclared collision between
//      two Primaries is an error.
//
//   2. Per-target layout. baosec and dabao carry different key slots (dabao has no CP_COOKIE or SWAP_KEY).
//      Because the offsets crate compiles every target module unconditionally, both maps are visible here
//      regardless of build config, and both are checked at compile time. Adding a target = adding its claim
//      list and two asserts below.
//
// The `#[cfg]`-free visibility is the whole point: a slot bug on baosec is caught even when
// building for dabao, and vice versa.
//
// Verified: the const fns compile on rustc 1.75, edition 2021, `#![no_std]` (SlotIndex
// destructuring in const context, and the two-slice walk avoids `&mut` params, which are not
// const-stable until 1.83). The real baosec and dabao maps pass; ERASE_PROOF-as-primary,
// a floating alias, and a primary/primary collision each fail the build.

pub use crate::*;

/// Whether a claim owns its slots or merely aliases into another claim's slots.
#[derive(Clone, Copy)]
pub enum SlotKind {
    /// Owns its slots. Two primaries may not share a slot.
    Primary,
    /// Deliberately shares slots with a primary. Must fall entirely within primary space.
    Alias,
}

/// A named claim on a run of data slots, derived from the backing `SlotIndex` so the numbers
/// cannot drift from the real constant.
pub struct DataClaim {
    pub name: &'static str,
    pub first: usize,
    pub count: usize,
    pub kind: SlotKind,
}

// Local const accessors. `SlotIndex::get_base`/`len` exist but are not `const fn`; reading the
// fields directly keeps this self-contained. (If you would rather, mark those two methods
// `const` upstream — `len` must become `range.end - range.start`, since `Range::len` is not
// const — and call them here instead.)
const fn slot_first(s: &SlotIndex) -> usize {
    match s {
        SlotIndex::Data(i, _, _) => *i,
        SlotIndex::DataRange(r, _, _) => r.start,
    }
}
const fn slot_count(s: &SlotIndex) -> usize {
    match s {
        SlotIndex::Data(_, _, _) => 1,
        SlotIndex::DataRange(r, _, _) => r.end - r.start,
    }
}

const fn primary(name: &'static str, s: &SlotIndex) -> DataClaim {
    DataClaim { name, first: slot_first(s), count: slot_count(s), kind: SlotKind::Primary }
}
const fn alias(name: &'static str, s: &SlotIndex) -> DataClaim {
    DataClaim { name, first: slot_first(s), count: slot_count(s), kind: SlotKind::Alias }
}

// ---- claims shared by every target (the `common`/offsets.rs page) ----
pub const COMMON_DATA_CLAIMS: &[DataClaim] = &[
    primary("SERIAL_NUMBER", &crate::offsets::SERIAL_NUMBER),
    primary("UUID", &crate::offsets::UUID),
    primary("IFR_HASH", &crate::offsets::IFR_HASH),
    primary("CP_ID", &crate::offsets::CP_ID),
    primary("BAO1_PUBKEY", &crate::offsets::BAO1_PUBKEY),
    primary("BAO2_PUBKEY", &crate::offsets::BAO2_PUBKEY),
    primary("BETA_PUBKEY", &crate::offsets::BETA_PUBKEY),
    primary("DEV_PUBKEY", &crate::offsets::DEV_PUBKEY),
    primary("COLLATERAL", &crate::offsets::COLLATERAL),
    primary("BOOT1_PK_RECEIPT_SLOT0", &crate::offsets::BOOT1_PK_RECEIPT_SLOT0),
    primary("BOOT1_PK_RECEIPT_SLOT1", &crate::offsets::BOOT1_PK_RECEIPT_SLOT1),
    primary("BOOT1_PK_RECEIPT_SLOT2", &crate::offsets::BOOT1_PK_RECEIPT_SLOT2),
    primary("BOOT1_PK_RECEIPT_SLOT3", &crate::offsets::BOOT1_PK_RECEIPT_SLOT3),
    primary("CLOCK_SCRAMBLE_PARAMS", &crate::offsets::CLOCK_SCRAMBLE_PARAMS),
    primary("ATE_RESERVED", &crate::offsets::ATE_RESERVED),
    primary("APPLICATION", &crate::offsets::APPLICATION),
];

// ---- baosec-specific claims ----
pub const BAOSEC_DATA_CLAIMS: &[DataClaim] = &[
    primary("NUISANCE_KEYS_0", &crate::offsets::baosec::NUISANCE_KEYS_0),
    primary("CHAFF_KEYS", &crate::offsets::baosec::CHAFF_KEYS),
    // deliberately the last slot of CHAFF_KEYS
    alias("ERASE_PROOF", &crate::offsets::baosec::ERASE_PROOF),
    primary("ROOT_SEED", &crate::offsets::baosec::ROOT_SEED),
    primary("RMA_KEY", &crate::offsets::baosec::RMA_KEY),
    primary("CP_COOKIE", &crate::offsets::baosec::CP_COOKIE),
    primary("SWAP_KEY", &crate::offsets::baosec::SWAP_KEY),
    primary("THE_FLAG_1", &crate::offsets::baosec::THE_FLAG_1),
    primary("NUISANCE_KEYS_1", &crate::offsets::baosec::NUISANCE_KEYS_1),
];

// ---- dabao-specific claims (no CP_COOKIE / SWAP_KEY; slots 258,259 free) ----
pub const DABAO_DATA_CLAIMS: &[DataClaim] = &[
    primary("NUISANCE_KEYS_0", &crate::offsets::dabao::NUISANCE_KEYS_0),
    primary("CHAFF_KEYS", &crate::offsets::dabao::CHAFF_KEYS),
    alias("ERASE_PROOF", &crate::offsets::dabao::ERASE_PROOF),
    primary("ROOT_SEED", &crate::offsets::dabao::ROOT_SEED),
    primary("RMA_KEY", &crate::offsets::dabao::RMA_KEY),
    primary("THE_FLAG_1", &crate::offsets::dabao::THE_FLAG_1),
    primary("NUISANCE_KEYS_1", &crate::offsets::dabao::NUISANCE_KEYS_1),
];

/// A named (common, target) pairing, so the host tool can iterate targets by name.
pub struct DataMap {
    pub name: &'static str,
    pub common: &'static [DataClaim],
    pub target: &'static [DataClaim],
}

pub const DATA_MAPS: &[DataMap] = &[
    DataMap { name: "baosec", common: COMMON_DATA_CLAIMS, target: BAOSEC_DATA_CLAIMS },
    DataMap { name: "dabao", common: COMMON_DATA_CLAIMS, target: DABAO_DATA_CLAIMS },
];

pub const DATA_OK: usize = 0;
pub const DATA_ERR_ZERO_COUNT: usize = 1;
pub const DATA_ERR_OUT_OF_RANGE: usize = 2;
pub const DATA_ERR_PRIMARY_OVERLAP: usize = 3;
pub const DATA_ERR_ALIAS_UNBACKED: usize = 4;

/// Paint every Primary onto a bitmap (rejecting Primary/Primary overlap and bad ranges), then
/// require every Alias slot to be backed by a Primary.
pub const fn check_data_map(common: &[DataClaim], target: &[DataClaim]) -> usize {
    let mut owned = [false; MAX_DATA_SLOTS];
    let slices = [common, target];

    // pass 1: primaries
    let mut si = 0;
    while si < slices.len() {
        let claims = slices[si];
        let mut i = 0;
        while i < claims.len() {
            let first = claims[i].first;
            let count = claims[i].count;
            if count == 0 {
                return DATA_ERR_ZERO_COUNT;
            }
            if first >= MAX_DATA_SLOTS || count > MAX_DATA_SLOTS - first {
                return DATA_ERR_OUT_OF_RANGE;
            }
            if let SlotKind::Primary = claims[i].kind {
                let mut s = first;
                while s < first + count {
                    if owned[s] {
                        return DATA_ERR_PRIMARY_OVERLAP;
                    }
                    owned[s] = true;
                    s += 1;
                }
            }
            i += 1;
        }
        si += 1;
    }

    // pass 2: aliases must land inside primary space
    let mut si = 0;
    while si < slices.len() {
        let claims = slices[si];
        let mut i = 0;
        while i < claims.len() {
            if let SlotKind::Alias = claims[i].kind {
                let first = claims[i].first;
                let count = claims[i].count;
                let mut s = first;
                while s < first + count {
                    if !owned[s] {
                        return DATA_ERR_ALIAS_UNBACKED;
                    }
                    s += 1;
                }
            }
            i += 1;
        }
        si += 1;
    }
    DATA_OK
}

/// Cross-check: every slot the runtime iterates for ACL enforcement (`DATA_SLOTS`, `KEY_SLOTS`)
/// must be owned by a Primary in the map. Catches the map and the ACL arrays drifting apart --
/// e.g. a key added to `KEY_SLOTS` but not registered here.
pub const fn check_coverage(common: &[DataClaim], target: &[DataClaim], slots: &[SlotIndex]) -> bool {
    let mut owned = [false; MAX_DATA_SLOTS];
    let slices = [common, target];
    let mut si = 0;
    while si < slices.len() {
        let claims = slices[si];
        let mut i = 0;
        while i < claims.len() {
            if let SlotKind::Primary = claims[i].kind {
                let first = claims[i].first;
                let count = claims[i].count;
                if first < MAX_DATA_SLOTS && count <= MAX_DATA_SLOTS - first {
                    let mut s = first;
                    while s < first + count {
                        owned[s] = true;
                        s += 1;
                    }
                }
            }
            i += 1;
        }
        si += 1;
    }

    let mut i = 0;
    while i < slots.len() {
        let first = slot_first(&slots[i]);
        let count = slot_count(&slots[i]);
        let mut s = first;
        while s < first + count {
            if s >= MAX_DATA_SLOTS || !owned[s] {
                return false;
            }
            s += 1;
        }
        i += 1;
    }
    true
}

// ---- compile-time enforcement, per target, config-independent ----

const _: () = assert!(
    check_data_map(COMMON_DATA_CLAIMS, BAOSEC_DATA_CLAIMS) != DATA_ERR_ZERO_COUNT,
    "baosec data map: a claim has zero length"
);
const _: () = assert!(
    check_data_map(COMMON_DATA_CLAIMS, BAOSEC_DATA_CLAIMS) != DATA_ERR_OUT_OF_RANGE,
    "baosec data map: a claim runs past MAX_DATA_SLOTS"
);
const _: () = assert!(
    check_data_map(COMMON_DATA_CLAIMS, BAOSEC_DATA_CLAIMS) != DATA_ERR_PRIMARY_OVERLAP,
    "baosec data map: two primaries overlap (declare one as alias() if intentional) - run `cargo run -p slot-check`"
);
const _: () = assert!(
    check_data_map(COMMON_DATA_CLAIMS, BAOSEC_DATA_CLAIMS) != DATA_ERR_ALIAS_UNBACKED,
    "baosec data map: an alias() falls outside all primaries - run `cargo run -p slot-check`"
);

const _: () = assert!(
    check_data_map(COMMON_DATA_CLAIMS, DABAO_DATA_CLAIMS) != DATA_ERR_ZERO_COUNT,
    "dabao data map: a claim has zero length"
);
const _: () = assert!(
    check_data_map(COMMON_DATA_CLAIMS, DABAO_DATA_CLAIMS) != DATA_ERR_OUT_OF_RANGE,
    "dabao data map: a claim runs past MAX_DATA_SLOTS"
);
const _: () = assert!(
    check_data_map(COMMON_DATA_CLAIMS, DABAO_DATA_CLAIMS) != DATA_ERR_PRIMARY_OVERLAP,
    "dabao data map: two primaries overlap (declare one as alias() if intentional) - run `cargo run -p slot-check`"
);
const _: () = assert!(
    check_data_map(COMMON_DATA_CLAIMS, DABAO_DATA_CLAIMS) != DATA_ERR_ALIAS_UNBACKED,
    "dabao data map: an alias() falls outside all primaries - run `cargo run -p slot-check`"
);

// coverage: the ACL arrays must be a subset of the map
const _: () = assert!(
    check_coverage(COMMON_DATA_CLAIMS, BAOSEC_DATA_CLAIMS, &crate::offsets::baosec::DATA_SLOTS),
    "baosec DATA_SLOTS contains a slot not registered as a primary in the data map"
);
const _: () = assert!(
    check_coverage(COMMON_DATA_CLAIMS, BAOSEC_DATA_CLAIMS, &crate::offsets::baosec::KEY_SLOTS),
    "baosec KEY_SLOTS contains a slot not registered as a primary in the data map"
);
const _: () = assert!(
    check_coverage(COMMON_DATA_CLAIMS, DABAO_DATA_CLAIMS, &crate::offsets::dabao::DATA_SLOTS),
    "dabao DATA_SLOTS contains a slot not registered as a primary in the data map"
);
const _: () = assert!(
    check_coverage(COMMON_DATA_CLAIMS, DABAO_DATA_CLAIMS, &crate::offsets::dabao::KEY_SLOTS),
    "dabao KEY_SLOTS contains a slot not registered as a primary in the data map"
);
