// ===================== ONE-WAY COUNTER SLOT CHECKER =====================
//
// Below is testing code generated by Claude Opus 4.8-high to make sure there are no collisions
// in the owc slot map. The idea is to have a build-time check that makes sure everything is consistent.
//
// Pure `no_std`, no test harness, no host toolchain: the `const _: () = assert!(...)` items
// at the bottom are evaluated during the normal cross-compile, so a bad slot map breaks the
// firmware build directly.
//
// Const panics cannot format, so the messages here are static. When one fires, run the
// host-side `owc-check` binary, which walks these same `pub` tables and reports exactly
// which claims collided.
//
// Footprint: these are `const` items, not `static`. Unreferenced consts emit no code or
// data into the firmware image, and the const fns are only ever called in const context.
//
// Verified to compile on rustc 1.75, edition 2021, `#![no_std]`.

pub use crate::*;

/// Total number of one-way counters in the array.
pub const OWC_TOTAL_SLOTS: usize = 256;
/// Slots below this are reserved for bootloader/xous use; at and above are user application slots.
pub const OWC_BOOT_SLOTS: usize = 128;

const fn claim(name: &'static str, first: usize, count: usize) -> OwcClaim { OwcClaim { name, first, count } }

/// Every slot claim in the boot region.
///
/// ADD AN ENTRY HERE whenever you allocate a slot. A constant that is not listed is
/// invisible to these checks and can be silently aliased by a later allocation.
//
// Macro-generated encodings register themselves via `<T as OneWayEncoding>::CLAIM`, which is
// derived from the `#[offset = N]` attribute. Editing that attribute alone is enough to trip
// the overlap assertion below; there is no literal here to drift out of sync.
pub const OWC_MAP: &[OwcClaim] = &[
    <UsbDefaultSpeed as OneWayEncoding>::CLAIM,
    claim("REQUIRE_PQ", REQUIRE_PQ, 1),
    claim("PQ_LOADER_REVOCATION_DUPE", PQ_LOADER_REVOCATION_DUPE_OFFSET, PUBKEY_SLOTS),
    claim("PQ_BOOT1_REVOCATION_DUPE", PQ_BOOT1_REVOCATION_DUPE_OFFSET, PUBKEY_SLOTS),
    claim("PQ_BOOT0_REVOCATION_DUPE", PQ_BOOT0_REVOCATION_DUPE_OFFSET, PUBKEY_SLOTS),
    claim("PQ_LOADER_REVOCATION", PQ_LOADER_REVOCATION_OFFSET, PUBKEY_SLOTS),
    claim("PQ_BOOT1_REVOCATION", PQ_BOOT1_REVOCATION_OFFSET, PUBKEY_SLOTS),
    claim("PQ_BOOT0_REVOCATION", PQ_BOOT0_REVOCATION_OFFSET, PUBKEY_SLOTS),
    claim("REQUIRE_PQ_DUPE", REQUIRE_PQ_DUPE, 1),
    claim("EARLY_BOOT_COUNT", EARLY_BOOT_COUNT, 1),
    claim("RESERVED0_ANTI_ROLLBACK", RESERVED0_ANTI_ROLLBACK, 1),
    claim("RESERVED1_ANTI_ROLLBACK", RESERVED1_ANTI_ROLLBACK, 1),
    claim("BOOT0_ANTI_ROLLBACK", BOOT0_ANTI_ROLLBACK, 1),
    claim("BOOT1_ANTI_ROLLBACK", BOOT1_ANTI_ROLLBACK, 1),
    claim("LOADER_ANTI_ROLLBACK", LOADER_ANTI_ROLLBACK, 1),
    claim("KERNEL_ANTI_ROLLBACK", KERNEL_ANTI_ROLLBACK, 1),
    claim("SWAP_ANTI_ROLLBACK", SWAP_ANTI_ROLLBACK, 1),
    claim("APP_ANTI_ROLLBACK", APP_ANTI_ROLLBACK, 1),
    claim("BAREMETAL_ANTI_ROLLBACK", BAREMETAL_ANTI_ROLLBACK, 1),
    claim("PARANOID_MODE", PARANOID_MODE, 1),
    claim("POSSIBLE_ATTACKS", POSSIBLE_ATTACKS, 1),
    claim("PARANOID_MODE_DUPE", PARANOID_MODE_DUPE, 1),
    claim("LOADER_REVOCATION_DUPE", LOADER_REVOCATION_DUPE_OFFSET, PUBKEY_SLOTS),
    claim("BOOT1_REVOCATION_DUPE", BOOT1_REVOCATION_DUPE_OFFSET, PUBKEY_SLOTS),
    claim("BOOT0_REVOCATION_DUPE", BOOT0_REVOCATION_DUPE_OFFSET, PUBKEY_SLOTS),
    <BootWaitCoding as OneWayEncoding>::CLAIM,
    <BoardTypeCoding as OneWayEncoding>::CLAIM,
    <AltBootCoding as OneWayEncoding>::CLAIM,
    claim("CP_BOOT_SETUP_DONE", CP_BOOT_SETUP_DONE, 1),
    claim("IN_SYSTEM_BOOT_SETUP_DONE", IN_SYSTEM_BOOT_SETUP_DONE, 1),
    claim("DEVELOPER_MODE", DEVELOPER_MODE, 1),
    claim("OEM_MODE", OEM_MODE, 1),
    claim("BOOT0_PUBKEY_FAIL", BOOT0_PUBKEY_FAIL, 1),
    claim("BOOT1_PUBKEY_FAIL", BOOT1_PUBKEY_FAIL, 1),
    <ExternalIdentifiers as OneWayEncoding>::CLAIM,
    claim("LOADER_REVOCATION", LOADER_REVOCATION_OFFSET, PUBKEY_SLOTS),
    claim("BOOT1_REVOCATION", BOOT1_REVOCATION_OFFSET, PUBKEY_SLOTS),
    claim("BOOT0_REVOCATION", BOOT0_REVOCATION_OFFSET, PUBKEY_SLOTS),
];

/// A primary revocation block paired with its hardened duplicate.
pub struct DupePair {
    pub name: &'static str,
    pub primary: usize,
    pub dupe: usize,
    pub distance: usize,
}

const fn dupe_pair(name: &'static str, primary: usize, dupe: usize, distance: usize) -> DupePair {
    DupePair { name, primary, dupe, distance }
}

/// Every (primary, duplicate) revocation pair, with the distance constant that
/// `validate_image()` / `pq_checks()` will actually use to reach the duplicate.
///
/// This is the invariant that matters most: both checkers index the duplicate as
/// `offset + i - DUPE_DISTANCE`, which is only correct if one shared distance constant
/// holds for *all three* partitions at once. Nothing else in the tree enforces that, and
/// getting it wrong reads an unrelated counter rather than failing loudly.
pub const OWC_DUPE_PAIRS: &[DupePair] = &[
    dupe_pair("loader", LOADER_REVOCATION_OFFSET, LOADER_REVOCATION_DUPE_OFFSET, REVOCATION_DUPE_DISTANCE),
    dupe_pair("boot1", BOOT1_REVOCATION_OFFSET, BOOT1_REVOCATION_DUPE_OFFSET, REVOCATION_DUPE_DISTANCE),
    dupe_pair("boot0", BOOT0_REVOCATION_OFFSET, BOOT0_REVOCATION_DUPE_OFFSET, REVOCATION_DUPE_DISTANCE),
    dupe_pair(
        "pq_loader",
        PQ_LOADER_REVOCATION_OFFSET,
        PQ_LOADER_REVOCATION_DUPE_OFFSET,
        PQ_REVOCATION_DUPE_DISTANCE,
    ),
    dupe_pair(
        "pq_boot1",
        PQ_BOOT1_REVOCATION_OFFSET,
        PQ_BOOT1_REVOCATION_DUPE_OFFSET,
        PQ_REVOCATION_DUPE_DISTANCE,
    ),
    dupe_pair(
        "pq_boot0",
        PQ_BOOT0_REVOCATION_OFFSET,
        PQ_BOOT0_REVOCATION_DUPE_OFFSET,
        PQ_REVOCATION_DUPE_DISTANCE,
    ),
];

/// Result codes. Const panics carry no data, so separate assertions on distinct codes are
/// what let the build tell you *which* kind of mistake you made.
pub const OWC_OK: usize = 0;
pub const OWC_ERR_ZERO_COUNT: usize = 1;
pub const OWC_ERR_OUT_OF_RANGE: usize = 2;
pub const OWC_ERR_OVERLAP: usize = 3;
pub const OWC_ERR_SPILLS_INTO_USER_REGION: usize = 4;

/// Paint every claimed slot onto a bitmap; a second claim on a painted slot is an overlap.
/// The bitmap approach also picks up zero-length runs (`PUBKEY_SLOTS == 0`), runs that fall
/// off the end of the array, and boot claims that reach into user application space.
pub const fn check_owc_map(map: &[OwcClaim]) -> usize {
    let mut used = [false; OWC_TOTAL_SLOTS];
    let mut i = 0;
    while i < map.len() {
        let first = map[i].first;
        let count = map[i].count;

        if count == 0 {
            return OWC_ERR_ZERO_COUNT;
        }
        // no wraparound, and stays inside the physical array
        if first >= OWC_TOTAL_SLOTS || count > OWC_TOTAL_SLOTS - first {
            return OWC_ERR_OUT_OF_RANGE;
        }
        // boot-region claims must not reach into the user application region
        if first + count > OWC_BOOT_SLOTS {
            return OWC_ERR_SPILLS_INTO_USER_REGION;
        }

        let mut s = first;
        while s < first + count {
            if used[s] {
                return OWC_ERR_OVERLAP;
            }
            used[s] = true;
            s += 1;
        }
        i += 1;
    }
    OWC_OK
}

/// Duplicates must sit exactly `distance` below their primary. Placing one above underflows
/// the subtraction in `hardened_get2()`.
pub const fn check_dupe_pairs(pairs: &[DupePair]) -> bool {
    let mut i = 0;
    while i < pairs.len() {
        let primary = pairs[i].primary;
        let dupe = pairs[i].dupe;
        let distance = pairs[i].distance;

        if dupe >= primary {
            return false;
        }
        if primary - distance != dupe {
            return false;
        }
        i += 1;
    }
    true
}

// ---- compile-time enforcement; no harness, no host toolchain, fires on the build ----

const _: () = assert!(
    check_owc_map(OWC_MAP) != OWC_ERR_ZERO_COUNT,
    "OWC slot map: a claim has zero length (is PUBKEY_SLOTS zero?)"
);
const _: () = assert!(
    check_owc_map(OWC_MAP) != OWC_ERR_OUT_OF_RANGE,
    "OWC slot map: a claim runs past the end of the counter array"
);
const _: () = assert!(
    check_owc_map(OWC_MAP) != OWC_ERR_SPILLS_INTO_USER_REGION,
    "OWC slot map: a boot-region claim spills into the user application region (>= 128)"
);
const _: () = assert!(
    check_owc_map(OWC_MAP) != OWC_ERR_OVERLAP,
    "OWC slot map: two claims overlap - run `cargo run -p owc-check` for the offending pair"
);
const _: () = assert!(
    check_dupe_pairs(OWC_DUPE_PAIRS),
    "OWC slot map: a revocation duplicate is not exactly DUPE_DISTANCE below its primary"
);
