#!/usr/bin/env bash

./stop_openocd

set -e

BIN="msc"

#TODO: use --message-format json to find the path to the executable instead of hard coded
cargo +nightly build --release --bin $BIN
openocd -f openocd.cfg -c "init_reset halt; program target/thumbv7m-none-eabi/release/$BIN verify reset exit"