[package]
name = "baremetal"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Baremetal target"

[dependencies]
xous = "0.9.66"
utralib = { version = "0.1.25", optional = true, default-features = false }
cramium-hal = { path = "../libs/cramium-hal", optional = true, default-features = false }
cramium-api = { path = "../libs/cramium-api", optional = true, default-features = false }
riscv = { version = "0.5.6", package = "xous-riscv" }
linked_list_allocator = { version = "0.10.5", optional = true }

[features]
artybio = ["utralib/artybio", "linked_list_allocator"]
cramium-soc = ["utralib/cramium-soc"]

verilator-only = []
debug-print = []
default = ["artybio", "debug-print"]
