// This file is autogenerated by xous-core/loader/src/generate_fonts.py. Do not edit.
// This makes probably bad assumptions about how link order is computed. Be suspicious of these offsets.
#![allow(dead_code)]
pub const FONT_BASE: usize = 0x20530000;
pub const BOLD_OFFSET: usize = 0x00000000;
pub const BOLD_LEN: usize = 0x00001774;
pub const EMOJI_OFFSET: usize = 0x00001774;
pub const EMOJI_LEN: usize = 0x00059170;
pub const HANZI_OFFSET: usize = 0x0005a8e4;
pub const HANZI_LEN: usize = 0x0010df64;
pub const REGULAR_OFFSET: usize = 0x00168848;
pub const REGULAR_LEN: usize = 0x00001610;
pub const SMALL_OFFSET: usize = 0x00169e58;
pub const SMALL_LEN: usize = 0x000010bc;
pub const FONT_TOTAL_LEN: usize = 0x0016af14;
