#![cfg_attr(rustfmt, rustfmt_skip)]
// DO NOT MAKE EDITS HERE because this file is automatically generated.
// The order of these modules affects the link order in the loader, which is referred to in the graphics engine.
// To make changes, see <xous_root>/services/graphics-server/src/blitstr2/codegen/main.go
#![allow(dead_code)]
#[cfg(not(feature = "cramium-soc"))]
pub const FONT_BASE: usize = 0x2053_0000;
#[cfg(feature = "cramium-soc")]
pub const FONT_BASE: usize = 0x6002_0000;

#[cfg(not(feature = "cramium-soc"))]
pub const EMOJI_OFFSET: usize = 0x0;
#[cfg(not(feature = "cramium-soc"))]
pub const EMOJI_LEN: usize = 0xab00;
#[cfg(not(feature = "cramium-soc"))]
pub const ZH_OFFSET: usize = 0xab00;
#[cfg(not(feature = "cramium-soc"))]
pub const ZH_LEN: usize = 0x3fea0;
#[cfg(not(feature = "cramium-soc"))]
pub const JA_OFFSET: usize = 0x4a9a0;
#[cfg(not(feature = "cramium-soc"))]
pub const JA_LEN: usize = 0x56920;
#[cfg(not(feature = "cramium-soc"))]
pub const KR_OFFSET: usize = 0xa12c0;
#[cfg(not(feature = "cramium-soc"))]
pub const KR_LEN: usize = 0x61600;
#[cfg(not(feature = "cramium-soc"))]
pub const BOLD_OFFSET: usize = 0x1028c0;
#[cfg(not(feature = "cramium-soc"))]
pub const BOLD_LEN: usize = 0x19e0;
#[cfg(not(feature = "cramium-soc"))]
pub const MONO_OFFSET: usize = 0x1042a0;
#[cfg(not(feature = "cramium-soc"))]
pub const MONO_LEN: usize = 0x19e0;
#[cfg(not(feature = "cramium-soc"))]
pub const REGULAR_OFFSET: usize = 0x105c80;
#[cfg(not(feature = "cramium-soc"))]
pub const REGULAR_LEN: usize = 0x19e0;
#[cfg(not(feature = "cramium-soc"))]
pub const TALL_OFFSET: usize = 0x107660;
#[cfg(not(feature = "cramium-soc"))]
pub const TALL_LEN: usize = 0x6780;
#[cfg(not(feature = "cramium-soc"))]
pub const SMALL_OFFSET: usize = 0x10dde0;
#[cfg(not(feature = "cramium-soc"))]
pub const SMALL_LEN: usize = 0x19e0;
#[cfg(not(feature = "cramium-soc"))]
pub const FONT_TOTAL_LEN: usize = 0x10f7c0;

#[cfg(feature = "cramium-soc")]
pub const EMOJI_OFFSET: usize = 0x0;
#[cfg(feature = "cramium-soc")]
pub const EMOJI_LEN: usize = 0xab00;
#[cfg(feature = "cramium-soc")]
pub const BOLD_OFFSET: usize = 0xab00;
#[cfg(feature = "cramium-soc")]
pub const BOLD_LEN: usize = 0x19e0;
#[cfg(feature = "cramium-soc")]
pub const MONO_OFFSET: usize = 0xc4e0;
#[cfg(feature = "cramium-soc")]
pub const MONO_LEN: usize = 0x19e0;
#[cfg(feature = "cramium-soc")]
pub const REGULAR_OFFSET: usize = 0xdec0;
#[cfg(feature = "cramium-soc")]
pub const REGULAR_LEN: usize = 0x19e0;
#[cfg(feature = "cramium-soc")]
pub const TALL_OFFSET: usize = 0xf8a0;
#[cfg(feature = "cramium-soc")]
pub const TALL_LEN: usize = 0x6780;
#[cfg(feature = "cramium-soc")]
pub const SMALL_OFFSET: usize = 0x16020;
#[cfg(feature = "cramium-soc")]
pub const SMALL_LEN: usize = 0x19e0;
#[cfg(feature = "cramium-soc")]
pub const FONT_TOTAL_LEN: usize = 0x17a00;

