// DO NOT MAKE EDITS HERE because this file is automatically generated.
// The order of these modules affects the link order in the loader, which is referred to in the graphics engine.
// To make changes, see <xous_root>/services/graphics-server/src/blitstr2/codegen/main.go
#![allow(dead_code)]
pub const FONT_BASE: usize = 0x20530000;
pub const EMOJI_OFFSET: usize = 0x0;
pub const EMOJI_LEN: usize = 0xab00;
pub const ZH_OFFSET: usize = 0xab00;
pub const ZH_LEN: usize = 0x3fea0;
pub const JA_OFFSET: usize = 0x4a9a0;
pub const JA_LEN: usize = 0x56920;
pub const KR_OFFSET: usize = 0xa12c0;
pub const KR_LEN: usize = 0x61600;
pub const BOLD_OFFSET: usize = 0x1028c0;
pub const BOLD_LEN: usize = 0x19e0;
pub const MONO_OFFSET: usize = 0x1042a0;
pub const MONO_LEN: usize = 0x19e0;
pub const REGULAR_OFFSET: usize = 0x105c80;
pub const REGULAR_LEN: usize = 0x19e0;
pub const TALL_OFFSET: usize = 0x107660;
pub const TALL_LEN: usize = 0x6780;
pub const SMALL_OFFSET: usize = 0x10dde0;
pub const SMALL_LEN: usize = 0x19e0;
pub const FONT_TOTAL_LEN: usize = 0x10f7c0;
