[package]
name = "perflib"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Performance counter tooling"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.12"
log = "0.4.14"
utralib = { version = "0.1.3", default-features = false }

[features]
precursor = ["utralib/precursor", "xous/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode", "xous/renode"]
default = []
