[package]
name = "persistent_store"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
"pddb" = {path="../../../../services/pddb"}
log = "0.4.14"

[dev-dependencies]
tempfile = "3"

[features]
std = []
