#![cfg_attr(rustfmt, rustfmt_skip)]
// DO NOT MAKE EDITS HERE because this file is automatically generated.
// The order of these modules affects the link order in the loader, which is referred to in the graphics engine.
// To make changes, see <xous_root>/libs/blitstr2/codegen/main.go
#![allow(dead_code)]
#[cfg(not(feature = "bao1x"))]
pub const FONT_BASE: usize = 0x2053_0000;

#[cfg(not(feature = "bao1x"))]
pub const EMOJI_OFFSET: usize = 0x0;
#[cfg(not(feature = "bao1x"))]
pub const EMOJI_LEN: usize = 0xab00;
#[cfg(not(feature = "bao1x"))]
pub const ZH_OFFSET: usize = 0xab00;
#[cfg(not(feature = "bao1x"))]
pub const ZH_LEN: usize = 0x3fea0;
#[cfg(not(feature = "bao1x"))]
pub const JA_OFFSET: usize = 0x4a9a0;
#[cfg(not(feature = "bao1x"))]
pub const JA_LEN: usize = 0x56920;
#[cfg(not(feature = "bao1x"))]
pub const KR_OFFSET: usize = 0xa12c0;
#[cfg(not(feature = "bao1x"))]
pub const KR_LEN: usize = 0x61600;
#[cfg(not(feature = "bao1x"))]
pub const BOLD_OFFSET: usize = 0x1028c0;
#[cfg(not(feature = "bao1x"))]
pub const BOLD_LEN: usize = 0x19e0;
#[cfg(not(feature = "bao1x"))]
pub const MONO_OFFSET: usize = 0x1042a0;
#[cfg(not(feature = "bao1x"))]
pub const MONO_LEN: usize = 0x19e0;
#[cfg(not(feature = "bao1x"))]
pub const REGULAR_OFFSET: usize = 0x105c80;
#[cfg(not(feature = "bao1x"))]
pub const REGULAR_LEN: usize = 0x19e0;
#[cfg(not(feature = "bao1x"))]
pub const TALL_OFFSET: usize = 0x107660;
#[cfg(not(feature = "bao1x"))]
pub const TALL_LEN: usize = 0x6780;
#[cfg(not(feature = "bao1x"))]
pub const SMALL_OFFSET: usize = 0x10dde0;
#[cfg(not(feature = "bao1x"))]
pub const SMALL_LEN: usize = 0x19e0;
#[cfg(not(feature = "bao1x"))]
pub const FONT_TOTAL_LEN: usize = 0x10f7c0;

