// AUTOGENERATED CODE on 2026-05-27T02:25:46.311537 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(biosao_bio_code, BM_BIOSAO_BIO_START, BM_BIOSAO_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	37f",
    // --- inline asm end ---
    "21:", // touch_init: @touch_init
    "li	a2, 25",
    "addi	a1, a0, 4",
    "slli	a2, a2, 10",
    "sh	a2, 0(a0)",
    "addi	a2, a0, 132",
    "22:", // .LBB1_1: =>This Inner Loop Header: Depth=1
    "sw	zero, 0(a1)",
    "addi	a1, a1, 4",
    "bne	a1, a2, 22b",
    "sw	zero, 132(a0)",
    "sb	zero, 136(a0)",
    "sw	zero, 140(a0)",
    "ret",
    "23:", // touch_update: @touch_update
    "beqz	a2, 25f",
    "li	a2, 25",
    "addi	a1, a0, 4",
    "slli	a2, a2, 10",
    "sh	a2, 0(a0)",
    "addi	a2, a0, 132",
    "24:", // .LBB2_2: =>This Inner Loop Header: Depth=1
    "sw	zero, 0(a1)",
    "addi	a1, a1, 4",
    "bne	a1, a2, 24b",
    "li	a1, 0",
    "sw	zero, 132(a0)",
    "sb	zero, 136(a0)",
    "sw	zero, 140(a0)",
    "j	36f",
    "25:", // .LBB2_4
    "lw	a3, 132(a0)",
    "addi	a5, a0, 4",
    "slli	a3, a3, 2",
    "add	a3, a3, a5",
    "sw	a1, 0(a3)",
    "lw	t1, 132(a0)",
    "addi	a1, a0, 132",
    "addi	a4, t1, 1",
    "sw	a4, 132(a0)",
    "26:", // .LBB2_5: =>This Inner Loop Header: Depth=1
    "lw	a3, 0(a5)",
    "addi	a5, a5, 4",
    "add	a2, a2, a3",
    "bne	a5, a1, 26b",
    "lbu	a5, 136(a0)",
    "li	a1, 32",
    "srli	t0, a2, 5",
    "bne	a4, a1, 28f",
    "bnez	a5, 27f",
    "li	a1, 1",
    "li	a2, 100",
    "sb	a1, 136(a0)",
    "sw	t0, 140(a0)",
    "sb	a2, 1(a0)",
    "27:", // .LBB2_9
    "lbu	a2, 0(a0)",
    "addi	t1, t1, -31",
    "sw	t1, 132(a0)",
    "j	29f",
    "28:", // .LBB2_10
    "srai	a1, a4, 31",
    "srli	a1, a1, 27",
    "add	a1, a1, a4",
    "lbu	a2, 0(a0)",
    "andi	a1, a1, -32",
    "sub	a4, a4, a1",
    "sw	a4, 132(a0)",
    "beqz	a5, 35f",
    "29:", // .LBB2_11
    "lw	a3, 140(a0)",
    "slli	a3, a3, 1",
    "beqz	a2, 30f",
    "bgeu	t0, a3, 34f",
    "lbu	a1, 1(a0)",
    "addi	a1, a1, -1",
    "andi	a3, a1, 255",
    "sb	a1, 1(a0)",
    "bnez	a3, 35f",
    "li	a2, 0",
    "j	33f",
    "30:", // .LBB2_15
    "bgeu	a3, t0, 31f",
    "lbu	a1, 1(a0)",
    "addi	a1, a1, -1",
    "andi	a2, a1, 255",
    "sb	a1, 1(a0)",
    "beqz	a2, 32f",
    "li	a2, 0",
    "j	35f",
    "31:", // .LBB2_18
    "li	a2, 0",
    "j	34f",
    "32:", // .LBB2_19
    "li	a2, 1",
    "33:", // .LBB2_20
    "sb	a2, 0(a0)",
    "34:", // .LBB2_21
    "li	a1, 100",
    "sb	a1, 1(a0)",
    "35:", // .LBB2_22
    "slli	a1, t0, 16",
    "or	a1, a1, a2",
    "36:", // .LBB2_23
    "mv	a0, a1",
    "ret",
    "37:", // main: @main
    "addi	sp, sp, -160",
    "sw	ra, 156(sp)", // 4-byte Folded Spill
    "sw	s0, 152(sp)", // 4-byte Folded Spill
    "sw	s1, 148(sp)", // 4-byte Folded Spill
    "lui	a0, 262656",
    "lui	a1, 262144",
    // --- inline asm begin ---
    "mv	x26, a0",
    // --- inline asm end ---
    "lui	a0, 512",
    // --- inline asm begin ---
    "mv	x25, a1",
    // --- inline asm end ---
    "li	a1, 25",
    // --- inline asm begin ---
    "mv	x24, a0",
    // --- inline asm end ---
    "slli	a1, a1, 10",
    "sh	a1, 4(sp)",
    "addi	a0, sp, 8",
    "addi	a1, sp, 136",
    "38:", // .LBB3_1: =>This Inner Loop Header: Depth=1
    "sw	zero, 0(a0)",
    "addi	a0, a0, 4",
    "bne	a0, a1, 38b",
    "li	a1, 0",
    "lui	a3, 262144",
    "sw	zero, 136(sp)",
    "sb	zero, 140(sp)",
    "sw	zero, 144(sp)",
    "lui	a0, 262656",
    // --- inline asm begin ---
    "mv	x24, a0",
    // --- inline asm end ---
    "li	s0, 0",
    // --- inline asm begin ---
    "mv	x23, a1",
    // --- inline asm end ---
    "addi	s1, a3, -1",
    "li	a2, 1",
    "39:", // .LBB3_3: =>This Loop Header: Depth=1
    // Child Loop BB3_4 Depth 2
    // Child Loop BB3_6 Depth 2
    "li	a0, 1000",
    "40:", // .LBB3_4: Parent Loop BB3_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a0, a0, -1",
    "bnez	a0, 40b",
    // in Loop: Header=BB3_3 Depth=1
    // --- inline asm begin ---
    "mv	a0, x31",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x25, a3",
    // --- inline asm end ---
    "41:", // .LBB3_6: Parent Loop BB3_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	a1, x21",
    // --- inline asm end ---
    "slli	a1, a1, 1",
    "bgez	a1, 41b",
    // in Loop: Header=BB3_3 Depth=1
    "and	a0, a0, s1",
    // --- inline asm begin ---
    "mv	a1, x31",
    // --- inline asm end ---
    "and	a1, a1, s1",
    "bltu	a0, a1, 42f",
    // in Loop: Header=BB3_3 Depth=1
    "xor	a1, a1, s1",
    "add	a1, a1, a0",
    "j	43f",
    "42:", // .LBB3_9: in Loop: Header=BB3_3 Depth=1
    "sub	a1, a1, a0",
    "43:", // .LBB3_10: in Loop: Header=BB3_3 Depth=1
    "addi	a0, sp, 4",
    "jal	ra, 23b",
    // --- inline asm begin ---
    "mv	a1, x30",
    // --- inline asm end ---
    "slli	a1, a1, 1",
    "bgez	a1, 44f",
    // in Loop: Header=BB3_3 Depth=1
    // --- inline asm begin ---
    "mv	x19, a0",
    // --- inline asm end ---
    "44:", // .LBB3_12: in Loop: Header=BB3_3 Depth=1
    "lui	a3, 262144",
    // --- inline asm begin ---
    "mv	x24, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, s0",
    // --- inline asm end ---
    "andi	a0, a0, 1",
    "bnez	a0, 45f",
    // in Loop: Header=BB3_3 Depth=1
    "li	a2, 0",
    // --- inline asm begin ---
    "mv	x23, a2",
    // --- inline asm end ---
    "j	39b",
    "45:", // .LBB3_14: in Loop: Header=BB3_3 Depth=1
    "lui	a0, 512",
    // --- inline asm begin ---
    "mv	x22, a0",
    // --- inline asm end ---
    "li	a2, 0",
    "j	39b"
);
